language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
branches:
  only:
    - dev
before_install:
  - gem install sass
  - npm install -g bower
  - npm install -g grunt-cli
before_script:
  - npm install
  - bower install
  - composer install
script: grunt testprod
notifications:
  email:
    on_success: always
    on_failure: always
