language: php
php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.2
branches:
  only:
    - dev
before_script:
  - npm install -g bower
  - npm install -g grunt-cli
  - bower install
  - composer install
script: grunt test
