title            : Pimp my Log
description      : Log viewer for your web server
production_url   : http://pimpmylog.com
author           :
    name    : Potsky
    email   : potsky@me.com
    github  : potsky
    twitter : potskymac
    link    : http://www.potsky.com

menus             : [ 'Getting Started' , 'Documentation' , 'Developer' , 'Blog' ]
rss_path          : /rss.xml
atom_path         : /atom.xml
url_github        : https://github.com/potsky/PimpMyLog
url_support       : http://support.pimpmylog.com
google_analytics  : UA-44146210-2
markdown          : redcarpet
pygments          : true
paginate          : 5
paginate_path     : /blog/page:num
permalink         : /:categories/:year/:month/:day/:title
excerpt_separator : <!--more-->
exclude           : [
    'bower.json',
    'bower_components',
    'Gruntfile.js',
    'node_modules',
    'package.json',
    'Gemfile',
    'Gemfile.lock',
    'README.md'
]

assets:
    root_url: '/assets'

images:
    root_url         : '/assets/img'
    retina           : true
    retina_suffix    : '@2x'
    lazy             : true
    lazy_placeholder : 'loading.gif'

disqus:
    shortname: 'pimpmylog'

